language: ruby

# whitelist
branches:  
  only:
    - master

services:  
    #Enable docker service inside travis
    - docker

before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    #build the image
    - docker build --no-cache -t oscarpublicar/aspnetcoretest ./src/AspNETCoreTest/
    #tag the build
    - docker tag oscarpublicar/aspnetcoretest:latest oscarpublicar/aspnetcoretest:v1
    #push the image to the repository
    - docker push oscarpublicar/aspnetcoretest