language: ruby

# whitelist
branches:  
  only:
    - master

services:  
    #Enable docker service inside travis
    - docker

before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:  
    #build the image
    - docker build --no-cache -t oscarbuitrago/aspnetcoretest
    #tag the build
    - docker tag oscarbuitrago/aspnetcoretest:latest oscarbuitrago/aspnetcoretest:v1
    #push the image to the repository
    - docker push oscarbuitrago/aspnetcoretest