version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/aspnetcore
hooks:
  AfterInstall:
    - location: shell/install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: shell/run.sh
      timeout: 3600
      runas: root
