version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/aspnetcore
hooks:
  ApplicationStop:
	- location: shell/stop.sh
	  timeout: 3600
	  runas: root
  AfterInstall:
    - location: shell/install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: shell/start.sh
      timeout: 3600
      runas: root
